# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: til-daily
app: til-daily
org: functionalstoic
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
functions:
  tilDaily:
    handler: handler.tilDaily
    events:
       - schedule: cron(0 1,15 * * ? *)
