# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: til-daily
app: til-daily
org: functionalstoic
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
iamRoleStatements:
  - Effect: Allow
    Action:
      - ssm: GetParameter
    Resource:
      - Fn::Join:
      - ':'
      - - arn:aws:ssm
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - parameter/*
functions:
  tilDaily:
    handler: handler.tilDaily
    environment:
      TRELLO_KEY: ${ssm:TRELLO_KEY}
      TRELLO_TOKEN: ${ssm:TRELLO_TOKEN}
      TRELLO_BOARD_ID: ${ssm:TRELLO_BOARD_ID}
      TWILIO_SID: ${ssm:TWILIO_SID}
      TWILIO_TOKEN: ${ssm:TWILIO_TOKEN}
      MY_PHONE_NUMBER: ${ssm:MY_PHONE_NUMBER}
      TWILIO_PHONE_NUMBER: ${ssm:TWILIO_PHONE_NUMBER}
    events:
       - schedule: cron(0 1,15 * * ? *)
